name: End-to-end tests
on: [push]
jobs:
  cypress-run-job1:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run E2E SauceDemo tests
        uses: cypress-io/github-action@v5
        with:
          spec: |
            cypress/e2e/regression/saucedemo
  cypress-run-job2:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run E2E TodoMVC tests
        uses: cypress-io/github-action@v5
        with:
          spec: |
            cypress/e2e/integration/reqresin
